### ISSUE TITLE
Cannot run iOS app .xcodeproj and .xcworkspace missing

### ISSUE THREAD

**Issue by j-q-in-berlin** [gematik/app-gemSekIdpAuth#10]
Hello, 
I have setup the necessary environment to run a Kotlin Multiplatform app and it does work for Android. But for iOS, I tried many things but it seems like there is always something missing.

I tried following the [official documentation](https://www.jetbrains.com/help/kotlin-multiplatform-dev/multiplatform-create-first-app.html#run-on-a-new-ios-simulated-device), but I cannot find the **.xcodeproj** or the **.xcworkspace**. 

Do you use Swift Package Manager to build the app? If so, can you explain how to generate the necessary files and get it running?

Thank you!

**Comment by Fokushvalen** [comment]
Hello @more2503, it's been a while since the latest update, so I was wondering if you have any status on this? We're very dependent on the authenticator app working, and currently it's delaying deliveries we have.
Is there any alternative in the meantime (X-Auth header in the browser is not an option for us)

**Comment by more2503** [comment]
GSIA is now working on iOS like on Android. Check latest update

**Comment by more2503** [comment]
You can get the link to Testflight in the FAQ for DiGAs in our gematik wiki. I will not share the exact link on GitHub.

**Comment by xinsight** [comment]
Thanks for the info!

If anyone is wondering, the links are:

https://wiki.gematik.de/display/TFD/FAQ
https://testflight.apple.com/join/brR4QueK
